controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    yaw_joint_position_controller:
      type: position_controllers/JointGroupPositionController

    bicep_joint_position_controller:
      type: position_controllers/JointGroupPositionController

    forearm_joint_position_controller:
      type: position_controllers/JointGroupPositionController

    pen_mount_joint_position_controller:
      type: position_controllers/JointGroupPositionController

yaw_joint_position_controller:
  ros__parameters:
    joints:
      - yaw_joint

bicep_joint_position_controller:
  ros__parameters:
    joints:
      - bicep_joint

forearm_joint_position_controller:
  ros__parameters:
    joints:
      - forearm_joint

pen_mount_joint_position_controller:
  ros__parameters:
    joints:
      - pen_mount_joint
